/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as KaniRouteImport } from './routes/kani'
import { Route as KashmirRouteImport } from './routes/kashmir'
import { Route as TheHouseRouteImport } from './routes/the-house'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const KaniRoute = KaniRouteImport.update({
  id: '/kani',
  path: '/kani',
  getParentRoute: () => rootRouteImport,
} as any)
const KashmirRoute = KashmirRouteImport.update({
  id: '/kashmir',
  path: '/kashmir',
  getParentRoute: () => rootRouteImport,
} as any)
const TheHouseRoute = TheHouseRouteImport.update({
  id: '/the-house',
  path: '/the-house',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/kani': typeof KaniRoute
  '/kashmir': typeof KashmirRoute
  '/the-house': typeof TheHouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/kani': typeof KaniRoute
  '/kashmir': typeof KashmirRoute
  '/the-house': typeof TheHouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/kani': typeof KaniRoute
  '/kashmir': typeof KashmirRoute
  '/the-house': typeof TheHouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/craftsmanship'
    | '/heritage'
    | '/journal'
    | '/kani'
    | '/kashmir'
    | '/the-house'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/craftsmanship'
    | '/heritage'
    | '/journal'
    | '/kani'
    | '/kashmir'
    | '/the-house'
  id:
    | '__root__'
    | '/'
    | '/craftsmanship'
    | '/heritage'
    | '/journal'
    | '/kani'
    | '/kashmir'
    | '/the-house'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  HeritageRoute: typeof HeritageRoute
  JournalRoute: typeof JournalRoute
  KaniRoute: typeof KaniRoute
  KashmirRoute: typeof KashmirRoute
  TheHouseRoute: typeof TheHouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kani': {
      id: '/kani'
      path: '/kani'
      fullPath: '/kani'
      preLoaderRoute: typeof KaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kashmir': {
      id: '/kashmir'
      path: '/kashmir'
      fullPath: '/kashmir'
      preLoaderRoute: typeof KashmirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-house': {
      id: '/the-house'
      path: '/the-house'
      fullPath: '/the-house'
      preLoaderRoute: typeof TheHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  HeritageRoute: HeritageRoute,
  JournalRoute: JournalRoute,
  KaniRoute: KaniRoute,
  KashmirRoute: KashmirRoute,
  TheHouseRoute: TheHouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
